package org.geysermc.rainbow.client.skull;

import com.google.common.collect.Iterables;
import com.mojang.authlib.GameProfile;
import com.mojang.authlib.properties.Property;
import com.mojang.authlib.properties.PropertyMap;
import com.mojang.datafixers.util.Either;
import net.minecraft.world.item.component.ResolvableProfile;
import org.geysermc.rainbow.client.mixin.ResolvableProfileAccessor;
import org.jspecify.annotations.Nullable;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

public final class CustomSkulls {
    private static final String BASE_CONFIGURATION_FILE = """
# --------------------------------
# Geyser Custom Skull Configuration Files
#
# This file is ignored with `add-custom-skull-blocks` disabled.
# See `config.yml` for the main set of configuration values
#
# Custom skulls with the player username, UUID, or texture specified in this file
# will be translated as custom blocks and be displayed in the inventory and on entities.
# --------------------------------

# --------------------------------
# This file was generated by Rainbow.
# --------------------------------

# Java player usernames
# Skins will be updated when Geyser starts and players will have to re-download
# the resource pack if any players had changed their skin.
player-usernames:
%s

# Java player UUIDs
# Skins will be updated when Geyser starts and players will have to re-download
# the resource pack if any players had changed their skin.
player-uuids:
%s

# The long string of characters found in the NBT of custom player heads
player-profiles:
%s

# The hash of the skin on Minecraft's skin server
skin-hashes:
""";

    private final Set<String> usernames = new HashSet<>();
    private final Set<UUID> uuids = new HashSet<>();
    private final Set<String> textures = new HashSet<>();

    public boolean withProfile(ResolvableProfile profile) {
        Either<GameProfile, ResolvableProfile.Partial> unpacked = ((ResolvableProfileAccessor) (Object) profile).invokeUnpack();
        return unpacked.left()
                .map(fullProfile -> {
                    Property texture = getTexture(fullProfile);
                    if (texture != null) {
                        return textures.add(texture.value());
                    }
                    return uuids.add(fullProfile.id());
                })
                .or(() -> unpacked.right()
                        .map(partialProfile -> {
                            Property texture = getTexture(partialProfile.properties());
                            if (texture != null) {
                                return textures.add(texture.value());
                            } else {
                                return partialProfile.id()
                                        .map(uuids::add)
                                        .or(() -> partialProfile.name().map(usernames::add))
                                        .orElse(false);
                            }
                        }))
                .orElseThrow();
    }

    public int usernames() {
        return usernames.size();
    }

    public int uuids() {
        return uuids.size();
    }

    public int textures() {
        return textures.size();
    }

    public String createConfig() {
        String usernameList = formatYamlList(usernames, Function.identity());
        String uuidList = formatYamlList(uuids, UUID::toString);
        String texturesList = formatYamlList(textures, Function.identity());
        return BASE_CONFIGURATION_FILE.formatted(usernameList, uuidList, texturesList);
    }

    private static <T> String formatYamlList(Collection<T> collection, Function<T, String> toString) {
        return collection.stream()
                .map(toString.andThen(s -> "- " + s))
                .collect(Collectors.joining("\n"));
    }

    private static @Nullable Property getTexture(GameProfile profile) {
        return getTexture(profile.properties());
    }

    private static @Nullable Property getTexture(PropertyMap map) {
        return Iterables.getFirst(map.get("textures"), null);
    }
}
